language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
after_script:
  - npm run coveralls
notifications:
  slack: intelliware:mzyu8GqG4LOunucRTp6texaW