language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
after_deploy:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run lh -- --perf=90 --pwa=90 --a11y=90 --bp=90 https://intelliware-coe-web.github.io/planning-poker/'
notifications:
  slack: intelliware:mzyu8GqG4LOunucRTp6texaW